"""remove_event_qr_unique

Revision ID: 5942cc8dd93c
Revises: ea50e1c1b65a
Create Date: 2026-07-26 11:20:20.664205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5942cc8dd93c'
down_revision: Union[str, Sequence[str], None] = 'ea50e1c1b65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_qr_code_reference'), 'events', ['qr_code_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_qr_code_reference'), table_name='events')
    # ### end Alembic commands ###
